AG-14751 - Clean up build generators in postinstall task 2 (#10391)
* AG-14751 - Clean up `postinstall` step of build (#10370)

* Move `generate-doc-references` and `generate-examples` deps to `nx dev` (`nx build` already had them)
* Removed `build:css` from `postinstall` as `nx dev` and `nx build` already had them in their deps (although, missing in `ag-grid-docs:test:vitest`)
* Add `build:css` to `vitest` deps - required for theme builder tests
* Add `generate-doc-references` to `vitest` deps - fails to build with error `[vite] (ssr) Error when evaluating SSR module /home/runner/work/ag-grid/ag-grid/documentation/ag-grid-docs/astro.config.mjs: Cannot find module 'ag-shared/processor' imported from '/home/runner/work/ag-grid/ag-grid/external/ag-website-shared/plugins/agLinkChecker.ts'`

* AG-14751 - Add copySrcFilesForGeneration as a dep for the test

`nx run ag-grid-generate-example-files:test:ci` was failing because of it

* AG-14751 - Add `build:css` as a dep for tests

Fixes `nx run ag-grid-community:test:ci`

* AG-14751 - Clean up projectRoot reference

* AG-14751 - Add `build` as a dep to styles test

Fixes `nx run @ag-grid-community/styles:build:styles` when run using `nx test`

* AG-14751 - Add `ag-shared:build` to module size test deps

Fixes `Error: Cannot find module '/Users/ttt/Work/Dev/ag-grid-2/node_modules/ag-shared/dist/package/scripts/junit-processor/src/processor.js'`